---
title: "build"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
library(tidyverse)
mtcars %>% 
  ggplot() +
  aes(x = "all") +
  geom_bar(position = position_dodge2(preserve = "single")) +
  geom_bar(data = . %>% complete(vs, gear, cyl) , 
           alpha = .2,
           position = position_dodge2(preserve = "single")) +
  stat_count(geom = "text",
             aes(label = ..count..),
             size = 5,
             position = 
               position_dodge2(width = 1,
                              preserve = "single")) + #BREAK
  aes(x = factor(vs)) + #BREAK
  aes(fill = factor(gear)) + #BREAK
  facet_grid(factor(cyl)~.) #BREAK
  
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "user", ...)`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 90%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

