---
title: "count while dicing"
---

```{r, include=FALSE}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F, echo = F)
library(flipbookr)
library(tidyverse)
```


```{r}
tribble(
  ~year, ~category, ~name,
  2015,  "A",       "1",
  2015,  "A",       "3",
  2015,  "A",       "5",
  2015,  "C",       "2",
  2015,  "C",       "4",
  2016,  "A",       "1",
  2016,  "A",       "4",
  2016,  "B",       "2",
  2016,  "B",       "3",
  2016,  "B",       "5",
  2017,  "B",       "1",
  2017,  "B",       "2",
  2017,  "B",       "3",
  2017,  "B",       "4",
  2017,  "C",       "5",
  2018,  "B",       "1",
  2018,  "B",       "2",
  2018,  "B",       "3",
  2018,  "B",       "4",
  2018,  "B",       "5"
) ->
base
```


```{r jitter, echo = F}
base %>% 
  group_by(category, year) %>% 
  mutate(pos = as.numeric(name) - 1) %>% 
  mutate(nudge_x = pos %% 3) %>% 
  mutate(nudge_y = pos %/% 3) %>% 
  mutate(num_cat = as.factor(category)) %>% 
  mutate(num_cat = as.numeric(num_cat)) %>% 
  ggplot() +
  aes(x = year, y = category) +
  geom_point(size = 3,
             alpha = .4) +
  aes(color = name) + 
  aes(x = year + nudge_x / 5) +
  aes(y = num_cat - nudge_y / 5) +
  labs(title = "No jittering; overplotting") +
  theme(legend.position = "bottom")
```

```{r, echo = T}
embed_flipbook("jitter", 
               font_size = 90, 
               use_embed_xaringan = T)
```

