---
title: "count while dicing"
---

```{r, include=FALSE}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F, echo = F)
library(flipbookr)
library(tidyverse)
```



```{r titanic, include = F}
library(tidyverse)
Titanic %>% 
  as.data.frame() %>% 
  uncount(weights = Freq) %>% 
  ggplot() +
  ggthemes::theme_igray() +
  aes(x = 1) + labs(x = NULL) +
  geom_bar(position = 
             position_dodge2(preserve = "single")) + #BREAK
  stat_count(geom = "text",
             aes(label = after_stat(count), 
                 y = after_stat(count) + 65),
             vjust = 0,
             size = 4,
             position = 
               position_dodge2(width = .9,
                               preserve = "single")) + #BREAK
  aes(fill = Survived) + 
  theme(legend.position = "top") +
  theme(legend.justification = 0) +
  scale_fill_viridis_d(option = "inferno") + #BREAK
  aes(x = Sex) + #BREAK
  facet_grid(Class~.) + 
  scale_y_continuous(expand = expansion(mult = c(.025, .3))) + #BREAK
  facet_grid(Class~Age) #BREAK

```


```{r}
embed_flipbook("titanic", 
               font_size = 90, 
               use_embed_xaringan = T,
               use_share_again = T,
               display_type = "output", 
               break_type = "user")
```


```{r}
embed_flipbook("titanic", 
               title = "code and titanic",
               rmd_path = "titanic_show_code.Rmd",
               url = "titanic_show_code.html",
               font_size = 90, 
               use_embed_xaringan = T,
               use_share_again = T)
```



```{r positions, include=T}
library(tidyverse)
set.seed(98789)
n <- 22
tibble(type = sample(LETTERS[1:3], n, replace = T),
       state = sample(state.abb[1:4], n, replace = T),
       event_occurs = sample(c("Yes", "No"), n, replace = T)) %>% 
  ggplot() +
  ggthemes::theme_igray() +
  geom_bar(position = "dodge2") + #ROTATE
  geom_bar(position = "identity") + #ROTATE
  geom_bar(position = "fill") + #ROTATE
  geom_bar(position = position_dodge2(preserve = "single")) + #ROTATE
  geom_bar(position = position_dodge2(preserve = "single", padding = .2)) + #ROTATE
  geom_bar(position = position_dodge2(preserve = "single", reverse = T)) + #ROTATE
  geom_bar(position = position_dodge2(preserve = "total", reverse = T)) + #ROTATE
  geom_bar(position = position_dodge(preserve = "single")) + #ROTATE
  geom_bar(position = position_dodge(width = 0.6)) + #ROTATE
  geom_bar(position = "stack") + #ROTATE
  geom_bar(position = "dodge") + #ROTATE
  aes(fill = event_occurs) + 
  theme(legend.position = "top") +
  theme(legend.justification = 0) +
  scale_fill_manual(values = c("plum4", "goldenrod1") ) + 
  aes(x = type) + 
  facet_grid(state~.) + 
  scale_y_continuous(expand = expansion(mult = c(.025, .3))) 
```


```{r}
embed_flipbook("positions",
               break_type =  "rotate",
               font_size = 80, 
               use_embed_xaringan = T,
               use_share_again = T,
               widths = c(1.2,1))
```



